const CARS_KEY="costarent_cars_v3";
const BOOKINGS_KEY="costarent_bookings_v3";
const STATUSES_BLOCKING=["Richiesta","Confermata","In corso"];
const defaultCars=[
{id:"panda-1",name:"Fiat Panda Hybrid 1",shortName:"Panda 1",plate:"Da definire",seats:4,fuel:"Mild Hybrid",summerPrice:40,lowPrice:30,status:"active",description:"Compatta, economica e ideale per città, mare e spostamenti locali.",colorClass:"panda"},
{id:"panda-2",name:"Fiat Panda Hybrid 2",shortName:"Panda 2",plate:"Da definire",seats:4,fuel:"Mild Hybrid",summerPrice:40,lowPrice:30,status:"active",description:"Seconda Panda per aumentare disponibilità nei periodi turistici.",colorClass:"panda-2"},
{id:"ypsilon-1",name:"Lancia Ypsilon",shortName:"Ypsilon",plate:"Da definire",seats:4,fuel:"Hybrid/Benzina",summerPrice:45,lowPrice:35,status:"active",description:"Più elegante e confortevole, adatta a weekend e clienti che cercano qualcosa in più.",colorClass:"ypsilon"}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function safeParse(v,f){try{return JSON.parse(v)||f}catch{return f}}
function getCars(){const s=safeParse(localStorage.getItem(CARS_KEY),null);if(!s||!Array.isArray(s)||!s.length){localStorage.setItem(CARS_KEY,JSON.stringify(defaultCars));return defaultCars}return s}
function saveCars(c){localStorage.setItem(CARS_KEY,JSON.stringify(c))}
function getBookings(){return safeParse(localStorage.getItem(BOOKINGS_KEY),[])}
function saveBookings(b){localStorage.setItem(BOOKINGS_KEY,JSON.stringify(b))}
function dateFromInput(value){if(!value)return null;const[y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)}
function addDays(date,days){const c=new Date(date);c.setDate(c.getDate()+days);return c}
function isSummer(d){const m=d.getMonth()+1;return m===7||m===8}
function formatDateIT(value){if(!value)return'-';const d=typeof value==='string'?dateFromInput(value):value;return d.toLocaleDateString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'})}
function getCar(id){return getCars().find(c=>c.id===id)||getCars()[0]}
function makeId(prefix='CR'){return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2,6)}`}
function calcEstimate(carId,start,end){if(!start||!end||end<=start)return null;const car=getCar(carId);let total=0,days=0,summerDays=0,lowDays=0;let cur=new Date(start);while(cur<end){if(isSummer(cur)){total+=Number(car.summerPrice);summerDays++}else{total+=Number(car.lowPrice);lowDays++}days++;cur=addDays(cur,1)}return{car,total,days,summerDays,lowDays}}
function rangesOverlap(aStart,aEnd,bStart,bEnd){return aStart<bEnd&&bStart<aEnd}
function availability(carId,startValue,endValue,ignoreId=null){const start=dateFromInput(startValue),end=dateFromInput(endValue);if(!start||!end||end<=start)return{ok:false,reason:'Date non valide'};const car=getCar(carId);if(!car||car.status!=='active')return{ok:false,reason:'Auto non attiva'};const conflict=getBookings().find(b=>b.id!==ignoreId&&b.carId===carId&&STATUSES_BLOCKING.includes(b.status)&&rangesOverlap(start,end,dateFromInput(b.startDate),dateFromInput(b.endDate)));if(conflict)return{ok:false,reason:`Conflitto con ${conflict.name} dal ${formatDateIT(conflict.startDate)} al ${formatDateIT(conflict.endDate)}.`};return{ok:true,reason:'Disponibile'}}
function statusPill(status){const cls={active:'active',maintenance:'maintenance',inactive:'inactive'}[status]||'done';const label={active:'Attiva',maintenance:'Manutenzione',inactive:'Non visibile'}[status]||status;return `<span class="status-pill ${cls}">${label}</span>`}
function bookingStatusPill(status){const cls={"Richiesta":"request","Confermata":"confirmed","In corso":"running","Conclusa":"done","Annullata":"cancelled"}[status]||'request';return `<span class="status-pill ${cls}">${status}</span>`}
function renderStats(){const bookings=getBookings();const cars=getCars();const revenue=bookings.filter(b=>b.status!=='Annullata').reduce((s,b)=>s+Number(b.total||0),0);const today=new Date();const todayStr=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;const busy=bookings.filter(b=>STATUSES_BLOCKING.includes(b.status)&&dateFromInput(b.startDate)<=dateFromInput(todayStr)&&dateFromInput(b.endDate)>dateFromInput(todayStr)).length;$('#statBookings').textContent=bookings.length;$('#statCars').textContent=cars.filter(c=>c.status==='active').length;$('#statRevenue').textContent=`${revenue}€`;$('#statBusy').textContent=busy}
function renderCars(){const body=$('#adminCarsBody');const cars=getCars();body.innerHTML=cars.map(c=>`<tr><td><strong>${c.name}</strong><br><small>${c.fuel||''} · ${c.plate||''}</small></td><td>${c.summerPrice}€ alta<br>${c.lowPrice}€ bassa</td><td>${statusPill(c.status)}</td><td><div class="inline-actions"><button class="mini-btn" data-edit-car="${c.id}">Modifica</button><button class="mini-btn danger" data-delete-car="${c.id}">Elimina</button></div></td></tr>`).join('');$$('[data-edit-car]').forEach(b=>b.onclick=()=>fillCarForm(b.dataset.editCar));$$('[data-delete-car]').forEach(b=>b.onclick=()=>deleteCar(b.dataset.deleteCar));renderManualCarOptions();renderStats()}
function fillCarForm(id){const c=getCar(id);$('#carFormTitle').textContent='Modifica auto';$('#carId').value=c.id;$('#carName').value=c.name||'';$('#carShort').value=c.shortName||'';$('#carPlate').value=c.plate||'';$('#carSeats').value=c.seats||4;$('#carFuel').value=c.fuel||'';$('#carSummer').value=c.summerPrice||0;$('#carLow').value=c.lowPrice||0;$('#carStatus').value=c.status||'active';$('#carDescription').value=c.description||'';window.location.hash='auto-admin'}
function clearCarForm(){('#carFormTitle');$('#carFormTitle').textContent='Aggiungi/modifica auto';$('#carForm').reset();$('#carId').value='';$('#carSeats').value=4;$('#carStatus').value='active'}
function deleteCar(id){const bookings=getBookings().filter(b=>b.carId===id&&b.status!=='Annullata');if(bookings.length){alert('Non puoi eliminare questa auto perché ha prenotazioni non annullate. Mettila in manutenzione/non visibile.');return}if(confirm('Eliminare questa auto?')){saveCars(getCars().filter(c=>c.id!==id));renderAll()}}
function renderManualCarOptions(){const select=$('#manualCar');if(!select)return;select.innerHTML=getCars().filter(c=>c.status==='active').map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}
function renderBookings(){const body=$('#adminBookingsBody');let bookings=getBookings().sort((a,b)=>a.startDate.localeCompare(b.startDate));const q=($('#bookingSearch')?.value||'').toLowerCase();const st=$('#statusFilter')?.value||'';if(q)bookings=bookings.filter(b=>[b.name,b.phone,b.carName,b.pickup,b.notes].join(' ').toLowerCase().includes(q));if(st)bookings=bookings.filter(b=>b.status===st);if(!bookings.length){body.innerHTML='<tr><td colspan="7" class="empty-row">Nessuna prenotazione trovata.</td></tr>';return}body.innerHTML=bookings.map(b=>`<tr><td><strong>${b.name}</strong><br><small>${b.phone||''}<br>${b.pickup||''}</small></td><td>${b.carName}</td><td>${formatDateIT(b.startDate)} → ${formatDateIT(b.endDate)}</td><td>${b.days}</td><td><strong>${b.total||0}€</strong></td><td>${bookingStatusPill(b.status)}</td><td><div class="inline-actions"><select data-status-booking="${b.id}"><option ${b.status==='Richiesta'?'selected':''}>Richiesta</option><option ${b.status==='Confermata'?'selected':''}>Confermata</option><option ${b.status==='In corso'?'selected':''}>In corso</option><option ${b.status==='Conclusa'?'selected':''}>Conclusa</option><option ${b.status==='Annullata'?'selected':''}>Annullata</option></select><button class="mini-btn danger" data-delete-booking="${b.id}">Elimina</button></div></td></tr>`).join('');$$('[data-status-booking]').forEach(s=>s.onchange=()=>changeBookingStatus(s.dataset.statusBooking,s.value));$$('[data-delete-booking]').forEach(b=>b.onclick=()=>deleteBooking(b.dataset.deleteBooking))}
function changeBookingStatus(id,status){const bookings=getBookings();const b=bookings.find(x=>x.id===id);if(!b)return;if(STATUSES_BLOCKING.includes(status)){const av=availability(b.carId,b.startDate,b.endDate,id);if(!av.ok){alert(av.reason);renderBookings();return}}b.status=status;saveBookings(bookings);renderAll()}
function deleteBooking(id){if(confirm('Eliminare definitivamente questa prenotazione demo?')){saveBookings(getBookings().filter(b=>b.id!==id));renderAll()}}
function updateManualEstimate(){const carId=$('#manualCar')?.value,start=$('#manualStart')?.value,end=$('#manualEnd')?.value;const est=calcEstimate(carId,dateFromInput(start),dateFromInput(end));if(!est){$('#manualEstimate').textContent='Seleziona auto e date.';return}const av=availability(carId,start,end);$('#manualEstimate').className=`estimate ${av.ok?'':'availability-box no'}`;$('#manualEstimate').textContent=`${est.car.name}: ${est.days} giorni, ${est.total}€. ${av.reason}`}
function addManualBooking(e){e.preventDefault();const carId=$('#manualCar').value,start=$('#manualStart').value,end=$('#manualEnd').value,status=$('#manualStatus').value;const est=calcEstimate(carId,dateFromInput(start),dateFromInput(end));if(!est){alert('Date non valide');return}if(STATUSES_BLOCKING.includes(status)){const av=availability(carId,start,end);if(!av.ok){alert(av.reason);return}}const booking={id:makeId(),createdAt:new Date().toISOString(),source:'Gestionale',status,carId,startDate:start,endDate:end,name:$('#manualName').value.trim(),phone:$('#manualPhone').value.trim(),pickup:$('#manualPickup').value.trim(),notes:$('#manualNotes').value.trim(),carName:est.car.name,days:est.days,total:est.total,summerDays:est.summerDays,lowDays:est.lowDays};saveBookings([...getBookings(),booking]);$('#manualBookingForm').reset();renderAll();alert('Prenotazione manuale salvata.')}
function exportCsv(){const rows=[['id','stato','cliente','telefono','auto','dal','al','giorni','totale','ritiro','note']];getBookings().forEach(b=>rows.push([b.id,b.status,b.name,b.phone,b.carName,b.startDate,b.endDate,b.days,b.total,b.pickup,b.notes]));const csv=rows.map(r=>r.map(v=>`"${String(v||'').replace(/"/g,'""')}"`).join(',')).join('\n');downloadFile('costarent-prenotazioni.csv',csv,'text/csv')}
function exportJson(){downloadFile('costarent-backup.json',JSON.stringify({cars:getCars(),bookings:getBookings(),exportedAt:new Date().toISOString()},null,2),'application/json')}
function downloadFile(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function importJsonFile(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(Array.isArray(data.cars))saveCars(data.cars);if(Array.isArray(data.bookings))saveBookings(data.bookings);renderAll();alert('Backup importato.')}catch{alert('File non valido')}};r.readAsText(file)}
function renderAll(){renderStats();renderCars();renderBookings();updateManualEstimate()}
function initAdmin(){if(sessionStorage.getItem('costarent_admin_ok')==='1'){showDashboard()}$('#loginBtn')?.addEventListener('click',()=>{if($('#adminPin').value==='1234'){sessionStorage.setItem('costarent_admin_ok','1');showDashboard()}else alert('PIN errato. Demo: 1234')});$('#carForm')?.addEventListener('submit',e=>{e.preventDefault();const id=$('#carId').value||makeId('CAR');const existing=getCars().filter(c=>c.id!==id);const color=$('#carName').value.toLowerCase().includes('ypsilon')?'ypsilon':(existing.length%2?'panda-2':'panda');const car={id,name:$('#carName').value.trim(),shortName:$('#carShort').value.trim(),plate:$('#carPlate').value.trim(),seats:Number($('#carSeats').value||4),fuel:$('#carFuel').value.trim(),summerPrice:Number($('#carSummer').value||0),lowPrice:Number($('#carLow').value||0),status:$('#carStatus').value,description:$('#carDescription').value.trim(),colorClass:getCar(id)?.colorClass||color};saveCars([...existing,car]);clearCarForm();renderAll()});$('#newCar')?.addEventListener('click',clearCarForm);$('#bookingSearch')?.addEventListener('input',renderBookings);$('#statusFilter')?.addEventListener('change',renderBookings);$('#manualBookingForm')?.addEventListener('submit',addManualBooking);['manualCar','manualStart','manualEnd'].forEach(id=>document.getElementById(id)?.addEventListener('change',updateManualEstimate));$('#exportCsv')?.addEventListener('click',exportCsv);$('#exportJson')?.addEventListener('click',exportJson);$('#importJson')?.addEventListener('change',e=>e.target.files[0]&&importJsonFile(e.target.files[0]));$('#resetDemo')?.addEventListener('click',()=>{if(confirm('Reset completo demo? Cancellerà auto modificate e prenotazioni.')){localStorage.removeItem(CARS_KEY);localStorage.removeItem(BOOKINGS_KEY);renderAll()}});renderAll()}
function showDashboard(){$('#adminLogin').classList.add('hidden');$('#adminDashboard').classList.remove('hidden');renderAll()}
initAdmin();
