const WHATSAPP_NUMBER = "390000000000"; // cambia con il numero aziendale, es. 393331234567
const CARS_KEY = "costarent_cars_v3";
const BOOKINGS_KEY = "costarent_bookings_v3";
const STATUSES_BLOCKING = ["Richiesta", "Confermata", "In corso"];

const defaultCars = [
  {id:"panda-1",name:"Fiat Panda Hybrid 1",shortName:"Panda 1",plate:"Da definire",seats:4,fuel:"Mild Hybrid",summerPrice:40,lowPrice:30,status:"active",description:"Compatta, economica e ideale per città, mare e spostamenti locali.",colorClass:"panda"},
  {id:"panda-2",name:"Fiat Panda Hybrid 2",shortName:"Panda 2",plate:"Da definire",seats:4,fuel:"Mild Hybrid",summerPrice:40,lowPrice:30,status:"active",description:"Seconda Panda per aumentare disponibilità nei periodi turistici.",colorClass:"panda-2"},
  {id:"ypsilon-1",name:"Lancia Ypsilon",shortName:"Ypsilon",plate:"Da definire",seats:4,fuel:"Hybrid/Benzina",summerPrice:45,lowPrice:35,status:"active",description:"Più elegante e confortevole, adatta a weekend e clienti che cercano qualcosa in più.",colorClass:"ypsilon"}
];

function safeParse(value, fallback){try{return JSON.parse(value)||fallback}catch{return fallback}}
function getCars(){const stored=safeParse(localStorage.getItem(CARS_KEY),null); if(!stored||!Array.isArray(stored)||!stored.length){localStorage.setItem(CARS_KEY,JSON.stringify(defaultCars));return defaultCars} return stored}
function saveCars(cars){localStorage.setItem(CARS_KEY,JSON.stringify(cars))}
function getBookings(){return safeParse(localStorage.getItem(BOOKINGS_KEY),[])}
function saveBookings(bookings){localStorage.setItem(BOOKINGS_KEY,JSON.stringify(bookings))}
function dateFromInput(value){if(!value)return null;const [y,m,d]=value.split("-").map(Number);return new Date(y,m-1,d)}
function addDays(date,days){const c=new Date(date);c.setDate(c.getDate()+days);return c}
function isSummer(date){const m=date.getMonth()+1;return m===7||m===8}
function formatDateIT(value){if(!value)return "-";const d=typeof value==="string"?dateFromInput(value):value;return d.toLocaleDateString("it-IT",{day:"2-digit",month:"2-digit",year:"numeric"})}
function getCar(id){return getCars().find(c=>c.id===id)||getCars()[0]}
function activeCars(){return getCars().filter(c=>c.status==="active")}
function calcEstimate(carId,start,end){if(!start||!end||end<=start)return null;const car=getCar(carId);let total=0,days=0,summerDays=0,lowDays=0;let cur=new Date(start);while(cur<end){if(isSummer(cur)){total+=Number(car.summerPrice);summerDays++}else{total+=Number(car.lowPrice);lowDays++}days++;cur=addDays(cur,1)}return{car,total,days,summerDays,lowDays}}
function rangesOverlap(aStart,aEnd,bStart,bEnd){return aStart<bEnd&&bStart<aEnd}
function availability(carId,startValue,endValue,ignoreId=null){const start=dateFromInput(startValue),end=dateFromInput(endValue);if(!start||!end||end<=start)return{ok:false,reason:"Date non valide"};const car=getCar(carId);if(!car||car.status!=="active")return{ok:false,reason:"Auto non prenotabile"};const conflict=getBookings().find(b=>b.id!==ignoreId&&b.carId===carId&&STATUSES_BLOCKING.includes(b.status)&&rangesOverlap(start,end,dateFromInput(b.startDate),dateFromInput(b.endDate)));if(conflict)return{ok:false,reason:`Auto già impegnata dal ${formatDateIT(conflict.startDate)} al ${formatDateIT(conflict.endDate)} (${conflict.status}).`};return{ok:true,reason:"Auto disponibile nelle date selezionate."}}
function makeId(prefix="CR"){return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2,6)}`}

let selectedCarId = activeCars()[0]?.id || defaultCars[0].id;
let currentStep=1;

const $=sel=>document.querySelector(sel);
const $$=sel=>document.querySelectorAll(sel);

function renderFleet(){const cars=activeCars();const fleetGrid=$("#fleetGrid"), choices=$("#carChoiceGrid"), prices=$("#pricesBody");
 if(!cars.length){if(fleetGrid)fleetGrid.innerHTML='<p class="notice">Nessuna auto attiva. Vai nel gestionale e attiva almeno un veicolo.</p>';return}
 if(!cars.find(c=>c.id===selectedCarId)) selectedCarId=cars[0].id;
 if(fleetGrid) fleetGrid.innerHTML=cars.map((car,i)=>`<article class="fleet-card ${i===2?'featured':''}"><div class="fleet-top"><span class="badge">${car.fuel||'Auto'}</span><span class="price-tag">${car.lowPrice}€ / ${car.summerPrice}€</span></div><div class="fleet-car ${car.colorClass||'panda'}"></div><h3>${car.name}</h3><p>${car.description||''}</p><ul class="features"><li>${car.seats||4} posti</li><li>${car.fuel||'-'}</li><li>Alta stagione ${car.summerPrice}€</li></ul><button class="text-link" type="button" data-select-car="${car.id}">Prenota questa auto →</button></article>`).join("");
 if(choices) choices.innerHTML=cars.map(car=>`<button class="car-choice ${car.id===selectedCarId?'selected':''}" type="button" data-select-car="${car.id}"><span class="car-icon ${car.colorClass||'panda'}"></span><span><h4>${car.name}</h4><p>${car.description||''}</p></span><span class="price-tag">${car.lowPrice}€ / ${car.summerPrice}€</span></button>`).join("");
 if(prices) prices.innerHTML=getCars().map(car=>`<tr><td><strong>${car.name}</strong><br><small>${car.fuel||''} · ${car.plate||''}</small></td><td>${car.summerPrice}€/giorno</td><td>${car.lowPrice}€/giorno</td><td>${statusPill(car.status)}</td></tr>`).join("");
 $$('[data-select-car]').forEach(btn=>btn.addEventListener('click',()=>{selectedCarId=btn.dataset.selectCar;renderFleet();updateEstimate();$('#prenota')?.scrollIntoView({behavior:'smooth'});setStep(1)}));
}
function statusPill(status){const map={active:["Attiva","active"],maintenance:["Manutenzione","maintenance"],inactive:["Non visibile","inactive"]};const [label,cls]=map[status]||[status,"done"];return `<span class="status-pill ${cls}">${label}</span>`}
function bookingStatusPill(status){const cls={"Richiesta":"request","Confermata":"confirmed","In corso":"running","Conclusa":"done","Annullata":"cancelled"}[status]||"request";return `<span class="status-pill ${cls}">${status}</span>`}
function values(){return{carId:selectedCarId,startDate:$('#startDate')?.value||'',endDate:$('#endDate')?.value||'',name:$('#name')?.value.trim()||'',phone:$('#phone')?.value.trim()||'',pickup:$('#pickup')?.value.trim()||'',notes:$('#notes')?.value.trim()||''}}
function updateEstimate(){const v=values();const est=calcEstimate(v.carId,dateFromInput(v.startDate),dateFromInput(v.endDate));const av=availability(v.carId,v.startDate,v.endDate);const availabilityBox=$('#availabilityBox'), estimate=$('#estimate'), summary=$('#summaryCard');if(!est){if(availabilityBox){availabilityBox.className='availability-box';availabilityBox.textContent='Seleziona date valide.'}if(estimate)estimate.textContent='Completa i passaggi.';if(summary)summary.innerHTML='';return}if(availabilityBox){availabilityBox.className=`availability-box ${av.ok?'ok':'no'}`;availabilityBox.textContent=av.reason}if(estimate)estimate.textContent=`${est.car.name}: ${est.days} giorni · stima ${est.total}€.`;if(summary)summary.innerHTML=`<div class="summary-row"><span>Auto</span><strong>${est.car.name}</strong></div><div class="summary-row"><span>Periodo</span><strong>${formatDateIT(v.startDate)} → ${formatDateIT(v.endDate)}</strong></div><div class="summary-row"><span>Giorni</span><strong>${est.days}</strong></div><div class="summary-row"><span>Alta stagione</span><strong>${est.summerDays}</strong></div><div class="summary-row"><span>Bassa stagione</span><strong>${est.lowDays}</strong></div><div class="summary-row"><span>Totale indicativo</span><strong>${est.total}€</strong></div><div class="summary-row"><span>Disponibilità</span><strong>${av.ok?'Disponibile':'Non disponibile'}</strong></div>`}
function setStep(step){currentStep=Math.max(1,Math.min(4,step));$$('.form-screen').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===currentStep));$$('.booking-step').forEach(b=>b.classList.toggle('active',Number(b.dataset.stepTarget)===currentStep));if($('#prevStep'))$('#prevStep').style.visibility=currentStep===1?'hidden':'visible';if($('#nextStep'))$('#nextStep').style.display=currentStep===4?'none':'inline-flex';updateEstimate()}
function validateStep(target){const v=values();if(target>=3){const av=availability(v.carId,v.startDate,v.endDate);if(!av.ok){alert(av.reason);return false}}if(target>=4&&(!v.name||!v.phone)){alert('Inserisci nome e telefono.');return false}return true}
function payload(){const v=values();const est=calcEstimate(v.carId,dateFromInput(v.startDate),dateFromInput(v.endDate));if(!est)return null;return{id:makeId(),createdAt:new Date().toISOString(),status:'Richiesta',source:'Sito',...v,carName:est.car.name,days:est.days,total:est.total,summerDays:est.summerDays,lowDays:est.lowDays}}
function saveRequest(){const v=values();const av=availability(v.carId,v.startDate,v.endDate);if(!av.ok){alert(av.reason);return null}if(!v.name||!v.phone){alert('Inserisci nome e telefono.');return null}const p=payload();const bookings=getBookings();bookings.push(p);saveBookings(bookings);alert('Richiesta salvata nel gestionale demo. Apri admin.html per vederla.');updateEstimate();return p}
function whatsappMessage(p){return [`Ciao CostaRent, vorrei verificare disponibilità per un noleggio.`,`Nome: ${p.name}`,`Telefono: ${p.phone}`,`Auto: ${p.carName}`,`Dal: ${p.startDate}`,`Al: ${p.endDate}`,`Durata: ${p.days} giorni`,`Stima sito: ${p.total}€`,`Ritiro/consegna: ${p.pickup||'da concordare'}`,p.notes?`Note: ${p.notes}`:'Note: nessuna'].join('\n')}
function initPublic(){if($('#year'))$('#year').textContent=new Date().getFullYear();$('#navToggle')?.addEventListener('click',()=>{const open=$('#nav').classList.toggle('open');$('#navToggle').setAttribute('aria-expanded',open?'true':'false')});$$('.nav a').forEach(a=>a.addEventListener('click',()=>$('#nav')?.classList.remove('open')));renderFleet();setStep(1);['startDate','endDate','name','phone','pickup','notes'].forEach(id=>{document.getElementById(id)?.addEventListener('input',updateEstimate);document.getElementById(id)?.addEventListener('change',updateEstimate)});$('#nextStep')?.addEventListener('click',()=>{const target=currentStep+1;if(validateStep(target))setStep(target)});$('#prevStep')?.addEventListener('click',()=>setStep(currentStep-1));$$('.booking-step').forEach(b=>b.addEventListener('click',()=>{const target=Number(b.dataset.stepTarget);if(validateStep(target))setStep(target)}));$('#saveDemoBooking')?.addEventListener('click',saveRequest);$('#bookingForm')?.addEventListener('submit',e=>{e.preventDefault();const p=saveRequest();if(!p)return;if(WHATSAPP_NUMBER==='390000000000'){alert('Richiesta salvata. Per WhatsApp configura WHATSAPP_NUMBER in app.js.');return}window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(whatsappMessage(p))}`,'_blank','noopener,noreferrer')});$('#directWhatsapp')?.addEventListener('click',e=>{e.preventDefault();if(WHATSAPP_NUMBER==='390000000000'){alert('Configura WHATSAPP_NUMBER in app.js.');return}window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent('Ciao CostaRent, vorrei informazioni sul noleggio auto.')}`,'_blank','noopener,noreferrer')});updateEstimate()}
initPublic();
